spring.application.name=ecommerce
#Uygulama Adı
spring.datasource.url=jdbc:postgresql://localhost:5432/E-Commerce
#PostgreSQL Bağlantı Bilgileri
spring.datasource.username=postgres
spring.datasource.password=5353

#JPA / Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect